name: Flutter CI

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    # Menambahkan ini agar semua perintah otomatis masuk ke folder setor_in
    defaults:
      run:
        working-directory: ./setor_in 

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: 🐦 Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: 📦 Install Dependencies
        run: flutter pub get

      - name: 🧪 Run Tests
        run: flutter test
        continue-on-error: true

      - name: 🏗️ Build APK
        run: flutter build apk --release

      - name: 📤 Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          # Jalur path harus diawali dengan folder proyek Anda
          path: setor_in/build/app/outputs/flutter-apk/*.apk

      - name: 🚀 Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          name: "Release ${{ github.ref_name }}"
          files: setor_in/build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 📲 Send APK to Telegram
        uses: appleboy/telegram-action@v1.0.1
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          document: setor_in/build/app/outputs/flutter-apk/app-release.apk
          message: |
            📦 Ini adalah file APK hasil build terbaru dari branch main.